### ISSUE TITLE
Issue after removing origin feature.

### ISSUE THREAD

**Issue by yura-chaikovsky** [angular-resource-sails/angular-resource-sails#10]
Is there other way to specify URL to sails server? 
I have several apps using the same Sails API and origin parameter works well. I have rolled back to 1.1.4, but if you have a minute, can you please tell what is reason to remove this feature and is it planned  to be in future versions? 
And thanks, angular-resource-sails is really great lib.

**Comment by xjpro** [comment]
I took this out because it was overriding io.socket. I have added it back in a new version (1.1.6) in a better way that doesn't mess with the regular socket. Check it out and let me know if this meets your requirements.
