### ISSUE TITLE
Cannot read property 'error'

### ISSUE THREAD

**Issue by stvogel** [angular-resource-sails/angular-resource-sails#22]
Hi there,

thanks a lot for this really neat piece of software.

I just stumbled over this error:

    TypeError: Cannot read property 'error' of undefined at sailsResource.js:212

Which is (in function `handleResponse(item, data, action, deferred, delegate)`):

    if (data.error || data.statusCode > 400 || isString(data)) {

I just changed that to:

    if (data && (data.error || data.statusCode > 400 || isString(data))) {

I'm not that deep into this module. I hope this is the correct solution.

**Comment by JasonMore** [comment]
@stvogel thanks. The response api changed a bit between sails versions and I don't think all the edge cases were discovered. There is a PR I need to review today which has the same fix so expect a version bump soon.

https://github.com/angular-resource-sails/angular-resource-sails/pull/21

**Comment by xjpro** [comment]
Fixed in PR #21
