### ISSUE TITLE
What if the client does not support socket.io ? 

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [angular-resource-sails/angular-resource-sails#25]
Hello,

I just wanted to know if there is any kind of fallbacks if the client does not support socket.io ? 

Thank you very much for your answer (and for your project ;) )

Guillaume Leclerc

**Comment by xjpro** [comment]
Not within angular-resource-sails, but socket.io itself supports AJAX long polling which is a fallback.

**Comment by GuillaumeLeclerc** [comment]
I know that, but then IE < 5.5 is not supported. Thank you for your information. (I will use it anyway I don't really need IE support)
