### ISSUE TITLE
Unable to create a non static action using GET

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [angular-resource-sails/angular-resource-sails#26]
Hello,

I have a model `User` who have notifications. I created a User resource. The correct request to retrieve notifications using sails is : `/user/:id/notifications`. This is a GET request. I was expecting to do something like this : 

```javascript
var User = sailsResource("user", ....);
var me = User.get({id : "me"});
var notifications = me.$notifications();
```
But because the notification is a GET request ([see](https://github.com/angular-resource-sails/angular-resource-sails/blob/master/src/sailsResource.js#L174))  I have to do this (which I think is not the optimal way) :

```javascript
var User = sailsResource("user", ....);
var me = User.get({id : "me"});
var id = me.id;
var notifications = User.$notifications({id : id});
```
Do you think we could/should add an option (called `static` for example) instead of relying on the HTTP method ? 

Thank you again for your very useful project !

**Comment by xjpro** [comment]
I think you could handle this case like this:

```javascript
var User = sailsResource('user',
    { notifications: { method: 'GET', isArray: true, url: '/user/:id/notifications' }}
};
var userNotifications = User.notifications({id: userId});
```

**Comment by GuillaumeLeclerc** [comment]
This is exactly my second example except I explicitly say where does userId comes from. It works great this way but I thought It would be great to pass the User object which contains the userId instead of the userId. Don't you think ?

**Comment by xjpro** [comment]
Could you do `me.$notifications()` (from your example)?

**Comment by GuillaumeLeclerc** [comment]
no because notification is a GET request and according to the code (see the link in my first message) the method should be added to the resource and not to the instances of that resource.

**Comment by xjpro** [comment]
Ah, I see. So yeah you can either do two calls or you could modify sailsResource to attach all of the GET calls onto the instance. I believe ngResource supports the latter so we have precedence to do that.

**Comment by GuillaumeLeclerc** [comment]
so get request would be attached to both right ?

**Comment by xjpro** [comment]
After reviewing $resource it says
```text
HTTP GET "class" actions: Resource.action([parameters], [success], [error])
non-GET "class" actions: Resource.action([parameters], postData, [success], [error])
non-GET instance actions: instance.$action([parameters], [success], [error])
```
So I guess GETs don't get added to the instance. How you do what you need to do with ngResource?

**Comment by GuillaumeLeclerc** [comment]
You are right I never worked with $resource but I just found it convenient to do this this way because sails allow get requests on models. But I completely understand you if you want to follow the original $resource behavior

**Comment by xjpro** [comment]
We could certainly support it, but I'd like to follow Angular's $resource example where possible.

**Comment by GuillaumeLeclerc** [comment]
As I said I understand your point. That's why I closed the issue
