### ISSUE TITLE
Errors are not catched

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [angular-resource-sails/angular-resource-sails#29]
Error callback are never called even if there was an error. (Using sails.js v0.11).

I dug into the code and according to the sails.js [documentation](http://sailsjs.org/documentation/reference/web-sockets/socket-client/io-socket-get) the callback need to take 2 arguments : 
- the body
- the jwr

In the library at the moment only the first argument is captured and given to `handleResponse`. This way the function cannot access the `statusCode` and potential errors because they are not in the body.

There might be several solution to this problem. I implemented one in a pull request.

Best,

Guillaume Leclerc

**Comment by ProfitWarning** [comment]
Thanks for your solution!
Had to change it a bit-
Line 226 
deferred.reject(data.error || data, item, data); 
does not work for me, because data.error is defined but empty so no jwr is send back
added (as quick fix):
if(data.statusCode > 400) {
    deffered.reject(data);
}
in my project.

**Comment by GuillaumeLeclerc** [comment]
I will check it out thank you
