### ISSUE TITLE
Errors not handled properly (error callback not called)

### ISSUE THREAD

**Issue by ckszabi** [angular-resource-sails/angular-resource-sails#31]
Error callback never gets fired, even if the resource is pointing to a non existing endpoint, even though the server responds with 404 codes (seen in WebSocket communication).

Steps to reproduce:
- create a sailsResource('for non existing endpoint');
- query() for data -> empty result is returned, success handler is called, which isn't the expected behavior

- Or just use the sample app and change the "Simples" identifier to something else (in HomeController.js)

Can we do something about it? Thanks in advance

**Comment by apinnecke** [comment]
Yep, +1 for me. Got an 401 status code, but success handler is called.

**Comment by xjpro** [comment]
Which version of sails?

**Comment by xjpro** [comment]
Should be working now in version 1.2.0
