### ISSUE TITLE
Model instance does not receive id on create

### ISSUE THREAD

**Issue by sean-nicholas** [angular-resource-sails/angular-resource-sails#35]
I created a new model instance as described in the documentation. When i call $save and pass a success callback there is no id, createdAt or updatedAt in the response object:
```javascript
newItem.$save(function(response) {
    // response has no id, createdAt or updatedAt
});
```
I tracked this down to https://github.com/angular-resource-sails/angular-resource-sails/blob/master/src/sailsResource.js#L334
handleResponse expects a JWR Object with body attribute but it gets directly passed the body attribute. I think a simple fix is to change 
```javascript
socket[method](url, data, function (response) {
```
to 
```javascript
socket[method](url, data, function (resData, response) {
```
Like it is done here https://github.com/angular-resource-sails/angular-resource-sails/blob/master/src/sailsResource.js#L288 and here https://github.com/angular-resource-sails/angular-resource-sails/blob/master/src/sailsResource.js#L369

What do you think?

**Comment by xjpro** [comment]
Good catch. Can you submit a PR?

**Comment by sean-nicholas** [comment]
Done

**Comment by xjpro** [comment]
Fixed by PR, thanks!
