### ISSUE TITLE
query() produces rubbish when only an id parameter is supplied

### ISSUE THREAD

**Issue by sean-nicholas** [angular-resource-sails/angular-resource-sails#37]
Running .query() with only an id parameter like so 

``` javascript
sailsResource('item').query({ id: 1 })
```

results in the following response:

``` json
[{
    "0": "T",
    "1": "e",
    "2": "s",
    "3": "t"
},
{
    "0": "2",
    "1": "0",
    "2": "1",
    "3": "6",
    "4": "-",
    "5": "0",
    "6": "3",
    "7": "-",
    "8": "0",
    "9": "3",
    "10": "T",
    "11": "1",
    "12": "8",
    "13": ":",
    "14": "0",
    "15": "8",
    "16": ":",
    "17": "3",
    "18": "6",
    "19": ".",
    "20": "2",
    "21": "9",
    "22": "1",
    "23": "Z"
},
{
    "0": "2",
    "1": "0",
    "2": "1",
    "3": "6",
    "4": "-",
    "5": "0",
    "6": "3",
    "7": "-",
    "8": "0",
    "9": "5",
    "10": "T",
    "11": "0",
    "12": "9",
    "13": ":",
    "14": "2",
    "15": "6",
    "16": ":",
    "17": "5",
    "18": "4",
    "19": ".",
    "20": "4",
    "21": "1",
    "22": "3",
    "23": "Z"
}]
```

query() assumes getting an array and instead it gets an object because I only supplied an id.
I think there are multiple ways to solve this. 
1. The easiest one is to give a warning in the docs and don't change a line of code
2. Do not create a new Resource in handleRequest. Instead create it based on the response (array or object)
3. Check before https://github.com/angular-resource-sails/angular-resource-sails/blob/master/src/sailsResource.js#L292 if data is an object then wrap it into an array.
4. Check in https://github.com/angular-resource-sails/angular-resource-sails/blob/master/src/sailsResource.js#L290 if data is an array, too. And add code to the else statement which creates a new resource if item isn't one.

3 and 4 are kind of the same but in 3 the users gets an array returned and in 4 an object. So the question is: If the user calls query() does she expects always an array or is returning an single object okay, too?

**Comment by xjpro** [comment]
What does ngResource do in this case? We've typically tried to match that behavior.

**Comment by sean-nicholas** [comment]
ngResource produces an error: 

```
Error: [$resource:badcfg] Error in resource configuration for action `query`. Expected response to contain an array but got an object
```

**Comment by xjpro** [comment]
If you want you can modify the code to return the same error as ngResource. Since we're essentially aping the same behavior that would be the most sensible change to make. Really though if you give an id you know it's going to return a single item and should just use .get instead. Up to you if you'd like to submit a PR.

**Comment by sean-nicholas** [comment]
Hey, your are right. Don't think a PR is necessary :)
