### ISSUE TITLE
don not support query multi ids

### ISSUE THREAD

**Issue by wjcody** [angular-resource-sails/angular-resource-sails#39]
such as Model.query({id :hisIds}, success,fail);  
When i try to query data by many ids, it will get error. I doubt why you don't support this usage.

**Comment by xjpro** [comment]
I wouldn't say it's not supported. It's just that nobody as of yet has apparently needed this feature badly enough to ensure it's implemented and working. What error do you get when you try this?

**Comment by wjcody** [comment]
I find the key 'id' is handled special. I want to search '{id: [id1, id2]}'. The correct urls are '/model/?id=id1' and '/model/?id=id2'. However, the urls I get is '/model/id1,id2'. The server will return the unknown column error.

**Comment by xjpro** [comment]
Seems reasonable. Can you do a PR that changes the URL building logic to handle this? I would think you could check if the id is an array and if so change it to URL query-params like you want.

**Comment by wjcody** [comment]
I used the sails.socket to solve this problem. It is nice If u can support this function. Thank you.
