### ISSUE TITLE
bower.json dependcy on sails.io.js 

### ISSUE THREAD

**Issue by bmatto** [angular-resource-sails/angular-resource-sails#4]
\# in url - causing bower to get confused.

**Comment by andyhu** [comment]
Looks like sails.io.js has been updated to 0.11.x, and mikermcneil said he has worked on this when doing upgrade https://github.com/balderdashy/sails.io.js/pull/31#issuecomment-66813939.
Can you please to check if it fixes the problem and upgrade bower dependency to 0.11.x? Also can we change angular dependency to 1.3.x?

**Comment by andyhu** [comment]
Also can we make jasmine devDependency?

**Comment by xjpro** [comment]
Thanks for the comments guy, and the PR andyhu. A new version of ARS is now available as v1.1.0 that is compatible with Sails 0.11 (and also uses a non-forked version of sails.io.js).

**Comment by andyhu** [comment]
Thanks @xjpro!
